### ISSUE TITLE
rejected promise not handled within 1 second: TimeoutError

### ISSUE THREAD

**Issue by muuvmuuv** [muuvmuuv/vscode-sundial#14]
```console
rejected promise not handled within 1 second: TimeoutError: Timeout awaiting 'request' for 5000ms
extensionHostProcess.js:700
stack trace: TimeoutError: Timeout awaiting 'request' for 5000ms
extensionHostProcess.js:700
	at ClientRequest.module.exports../node_modules/got/source/request-as-event-emitter.js.e.exports.n.once.t (/Users/marvinheilemann/.vscode/extensions/muuvmuuv.vscode-sundial-1.3.0/dist/extension.js:11:63981)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:187:15)
	at ClientRequest.module.exports../node_modules/@szmarczak/http-timer/source/index.js.e.exports.e.emit.a (/Users/marvinheilemann/.vscode/extensions/muuvmuuv.vscode-sundial-1.3.0/dist/extension.js:11:6506)
	at Immediate._ (/Users/marvinheilemann/.vscode/extensions/muuvmuuv.vscode-sundial-1.3.0/dist/extension.js:11:66803)
	at runCallback (timers.js:697:11)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
```

**Comment by muuvmuuv** [comment]
Never happened again
